version: "3.7"

services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro

  keycloak_ifood:
    container_name: keycloak_ifood
    image: quay.io/keycloak/keycloak:9.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - postgres_cadastro
